# site
baseurl: ''
url: https://shenlu89.github.io
author: shenlu89
title: "Shen Lu's Blog" # the name of your site, e.g. ACME Corp.

# markdown
markdown: kramdown
highlighter: rouge

# paginator
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num"

# google analytics
google_analytics_id: "Google Analytics ID"

# other configs
exclude: ["CNAME", "README.md"]
