permalink: /:year/:month/:day/:title/
url: http://shenlu89.github.io
author: Shen Lu
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM
#   auto_ids: true
#   toc_levels: 1..3
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     default_lang: html
#     css_class: 'hljs'

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

jekyll-archives:
  enabled: all
  layout: page

exclude: ["CNAME", "README.md"]
safe: true
plugins:
  - jekyll-paginate
  - jekyll-archives
paginate: 10
paginate_path: '/page:num'
permalink: '/:title'


# Gems
gems: [jekyll-paginate,jekyll-archives]