import { objToMap } from "./utils";

export const COUNTRY_NAME: any = objToMap({
  UZ: "Uzbekistan",
  PS: "Palestinian Territory, Occupied",
  QA: "Qatar",
  SA: "Saudi Arabia",
  AF: "Afghanistan",
  LB: "Lebanon",
  BH: "Bahrain",
  CY: "Cyprus",
  SY: "Syrian Arab Republic",
  TJ: "Tajikistan",
  TM: "Turkmenistan",
  AE: "United Arab Emirates",
  IR: "Iran, Islamic Republic of",
  IQ: "Iraq",
  OM: "Oman",
  PK: "Pakistan",
  IL: "Israel",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  VN: "Viet Nam",
  MV: "Maldives",
  PH: "Philippines",
  BD: "Bangladesh",
  BT: "Bhutan",
  BN: "Brunei Darussalam",
  KH: "Cambodia",
  TL: "Timor-Leste",
  SG: "Singapore",
  LK: "Sri Lanka",
  TH: "Thailand",
  NP: "Nepal",
  LA: "Lao People's Democratic Republic",
  YE: "Yemen",
  GE: "Georgia",
  TR: "Turkey",
  AM: "Armenia",
  AZ: "Azerbaijan",
  DT: "Disputed Territory",
  MY: "Malaysia",
  IO: "British Indian Ocean Territory",
  IN: "India",
  ID: "Indonesia",
  MM: "Myanmar",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  GU: "Guam",
  MH: "Marshall Islands",
  PN: "Pitcairn",
  WS: "Samoa",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  FJ: "Fiji",
  TK: "Tokelau",
  TO: "Tonga",
  TV: "Tuvalu",
  NR: "Nauru",
  NC: "New Caledonia",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  PW: "Palau",
  VA: "Holy See (Vatican City State)",
  MK: "Macedonia, the former Yugoslav Republic of",
  MT: "Malta",
  MC: "Monaco",
  PL: "Poland",
  RO: "Romania",
  SM: "San Marino",
  AL: "Albania",
  LV: "Latvia",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  BE: "Belgium",
  BA: "Bosnia and Herzegovina",
  BG: "Bulgaria",
  HR: "Croatia",
  CZ: "Czech Republic",
  DK: "Denmark",
  EE: "Estonia",
  FO: "Faroe Islands",
  FI: "Finland",
  GG: "Guernsey",
  IM: "Isle of Man",
  JE: "Jersey",
  DE: "Germany",
  GI: "Gibraltar",
  GL: "Greenland",
  SK: "Slovakia",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  AD: "Andorra",
  AT: "Austria",
  HU: "Hungary",
  IS: "Iceland",
  NL: "Netherlands",
  NO: "Norway",
  IE: "Ireland",
  AX: "Åland Islands",
  ME: "Montenegro",
  GY: "Guyana",
  FK: "Falkland Islands (Malvinas)",
  GF: "French Guiana",
  SR: "Suriname",
  UY: "Uruguay",
  PY: "Paraguay",
  PE: "Peru",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  GP: "Guadeloupe",
  HT: "Haiti",
  MQ: "Martinique",
  MS: "Montserrat",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  BB: "Barbados",
  BM: "Bermuda",
  KY: "Cayman Islands",
  CU: "Cuba",
  DM: "Dominica",
  DO: "Dominican Republic",
  GD: "Grenada",
  TT: "Trinidad and Tobago",
  TC: "Turks and Caicos Islands",
  AI: "Anguilla",
  AG: "Antigua and Barbuda",
  AW: "Aruba",
  BS: "Bahamas",
  JM: "Jamaica",
  EH: "Western Sahara",
  DZ: "Algeria",
  TN: "Tunisia",
  MA: "Morocco",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  GN: "Guinea",
  LY: "Libya",
  GW: "Guinea-Bissau",
  ML: "Mali",
  MR: "Mauritania",
  YT: "Mayotte",
  RW: "Rwanda",
  RE: "Réunion",
  SN: "Senegal",
  SL: "Sierra Leone",
  LS: "Lesotho",
  LR: "Liberia",
  MG: "Madagascar",
  MW: "Malawi",
  BJ: "Benin",
  BW: "Botswana",
  BF: "Burkina Faso",
  BI: "Burundi",
  CM: "Cameroon",
  CV: "Cape Verde",
  CF: "Central African Republic",
  TD: "Chad",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, The Democratic Republic of the",
  CI: "Côte d'Ivoire",
  DJ: "Djibouti",
  ER: "Eritrea",
  ET: "Ethiopia",
  GA: "Gabon",
  GM: "Gambia",
  GH: "Ghana",
  SO: "Somalia",
  SD: "Sudan",
  SZ: "Swaziland",
  TZ: "Tanzania, United Republic of",
  TG: "Togo",
  UG: "Uganda",
  MZ: "Mozambique",
  NE: "Niger",
  NG: "Nigeria",
  KE: "Kenya",
  GT: "Guatemala",
  BZ: "Belize",
  SV: "El Salvador",
  PA: "Panama",
  HM: "Heard Island and McDonald Islands",
  BV: "Bouvet Island",
  AQ: "Antarctica",
  MD: "Moldova",
  BY: "Belarus",
  MN: "Mongolia",
  MO: "Macao",
  HK: "Hong Kong",
  KP: "Korea, Democratic People's Republic of",
  KR: "Korea, Republic of",
  PM: "Saint Pierre and Miquelon",
  MF: "Saint Martin (French part)",
  BL: "Saint Barthélemy",
  AS: "American Samoa",
  CK: "Cook Islands",
  PF: "French Polynesia",
  SB: "Solomon Islands",
  UM: "United States Minor Outlying Islands",
  AU: "Australia",
  NZ: "New Zealand",
  PG: "Papua New Guinea",
  KI: "Kiribati",
  PT: "Portugal",
  FR: "France",
  GR: "Greece",
  ES: "Spain",
  GB: "United Kingdom",
  IT: "Italy",
  RS: "Serbia",
  BR: "Brazil",
  CL: "Chile",
  CO: "Colombia",
  EC: "Ecuador",
  AR: "Argentina",
  PR: "Puerto Rico",
  AN: "Netherlands Antilles",
  EG: "Egypt",
  MU: "Mauritius",
  ST: "Sao Tomé and Principe",
  SC: "Seychelles",
  GQ: "Equatorial Guinea",
  ZA: "South Africa",
  AO: "Angola",
  NA: "Namibia",
  MX: "Mexico",
  CR: "Costa Rica",
  HN: "Honduras",
  NI: "Nicaragua",
  GS: "South Georgia and the South Sandwich Islands",
  RU: "Russian Federation",
  UA: "Ukraine",
  CN: "China",
  TW: "Taiwan, Province of China",
  JP: "Japan",
  CA: "Canada",
  US: "United States",
  BO: "Bolivia, Plurinational States of",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  CW: "Curaçao",
  SX: "Sint Maarten (Dutch part)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  SS: "South Sudan",
  TF: "French Southern Territories",
  FM: "Micronesia, Federated States of ",
  VE: "Venezuela, Bolivarian Republic of",
});

export const CONSERVATION_STATUS: any = objToMap({
  EX: "Extinction",
  EW: "Extinct_in_the_wild",
  CR: "Critically_endangered",
  EN: "Critically_endangered",
  VU: "Vulnerable_species",
  NT: "Near-threatened_species",
  LC: "Least_concern",
  DD: "Data_deficient",
  NE: "Not_evaluated",
});

export const WIKI_URI = "https://en.wikipedia.org/wiki/";

export const IUCN_RED_LIST_URI = "http://apiv3.iucnredlist.org/api/v3/website/";

export const WORLD_110M =
  "https://s3-us-west-2.amazonaws.com/s.cdpn.io/95802/world-110m.json";
